//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.WcfPublicServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventDTO", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary.DTO")]
    [System.SerializableAttribute()]
    public partial class EventDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateTimeFinishField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateTimeStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LayoutIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTimeFinish {
            get {
                return this.DateTimeFinishField;
            }
            set {
                if ((this.DateTimeFinishField.Equals(value) != true)) {
                    this.DateTimeFinishField = value;
                    this.RaisePropertyChanged("DateTimeFinish");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTimeStart {
            get {
                return this.DateTimeStartField;
            }
            set {
                if ((this.DateTimeStartField.Equals(value) != true)) {
                    this.DateTimeStartField = value;
                    this.RaisePropertyChanged("DateTimeStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUrl {
            get {
                return this.ImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrlField, value) != true)) {
                    this.ImageUrlField = value;
                    this.RaisePropertyChanged("ImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LayoutId {
            get {
                return this.LayoutIdField;
            }
            set {
                if ((this.LayoutIdField.Equals(value) != true)) {
                    this.LayoutIdField = value;
                    this.RaisePropertyChanged("LayoutId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvalidEventException", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary.CustomExceptions")]
    [System.SerializableAttribute()]
    public partial class InvalidEventException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomError {
            get {
                return this.CustomErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomErrorField, value) != true)) {
                    this.CustomErrorField = value;
                    this.RaisePropertyChanged("CustomError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CanNotCreateEventSeatException", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary.CustomExceptions")]
    [System.SerializableAttribute()]
    public partial class CanNotCreateEventSeatException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomError {
            get {
                return this.CustomErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomErrorField, value) != true)) {
                    this.CustomErrorField = value;
                    this.RaisePropertyChanged("CustomError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CanNotDeleteEventException", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary.CustomExceptions")]
    [System.SerializableAttribute()]
    public partial class CanNotDeleteEventException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomError {
            get {
                return this.CustomErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomErrorField, value) != true)) {
                    this.CustomErrorField = value;
                    this.RaisePropertyChanged("CustomError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventInfoDTO", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary.DTO")]
    [System.SerializableAttribute()]
    public partial class EventInfoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LayoutDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LayoutNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VenueAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VenueDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VenueNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VenuePhoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LayoutDescription {
            get {
                return this.LayoutDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.LayoutDescriptionField, value) != true)) {
                    this.LayoutDescriptionField = value;
                    this.RaisePropertyChanged("LayoutDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LayoutName {
            get {
                return this.LayoutNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LayoutNameField, value) != true)) {
                    this.LayoutNameField = value;
                    this.RaisePropertyChanged("LayoutName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VenueAddress {
            get {
                return this.VenueAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.VenueAddressField, value) != true)) {
                    this.VenueAddressField = value;
                    this.RaisePropertyChanged("VenueAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VenueDescription {
            get {
                return this.VenueDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.VenueDescriptionField, value) != true)) {
                    this.VenueDescriptionField = value;
                    this.RaisePropertyChanged("VenueDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VenueName {
            get {
                return this.VenueNameField;
            }
            set {
                if ((object.ReferenceEquals(this.VenueNameField, value) != true)) {
                    this.VenueNameField = value;
                    this.RaisePropertyChanged("VenueName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VenuePhone {
            get {
                return this.VenuePhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.VenuePhoneField, value) != true)) {
                    this.VenuePhoneField = value;
                    this.RaisePropertyChanged("VenuePhone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventAreaDTO", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary.DTO")]
    [System.SerializableAttribute()]
    public partial class EventAreaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CoordXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CoordYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EventIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LayoutIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CoordX {
            get {
                return this.CoordXField;
            }
            set {
                if ((this.CoordXField.Equals(value) != true)) {
                    this.CoordXField = value;
                    this.RaisePropertyChanged("CoordX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CoordY {
            get {
                return this.CoordYField;
            }
            set {
                if ((this.CoordYField.Equals(value) != true)) {
                    this.CoordYField = value;
                    this.RaisePropertyChanged("CoordY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EventId {
            get {
                return this.EventIdField;
            }
            set {
                if ((this.EventIdField.Equals(value) != true)) {
                    this.EventIdField = value;
                    this.RaisePropertyChanged("EventId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LayoutId {
            get {
                return this.LayoutIdField;
            }
            set {
                if ((this.LayoutIdField.Equals(value) != true)) {
                    this.LayoutIdField = value;
                    this.RaisePropertyChanged("LayoutId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventSeatDTO", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary.DTO")]
    [System.SerializableAttribute()]
    public partial class EventSeatDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EventAreaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EventAreaId {
            get {
                return this.EventAreaIdField;
            }
            set {
                if ((this.EventAreaIdField.Equals(value) != true)) {
                    this.EventAreaIdField = value;
                    this.RaisePropertyChanged("EventAreaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Number {
            get {
                return this.NumberField;
            }
            set {
                if ((this.NumberField.Equals(value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Row {
            get {
                return this.RowField;
            }
            set {
                if ((this.RowField.Equals(value) != true)) {
                    this.RowField = value;
                    this.RaisePropertyChanged("Row");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfPublicServiceReference.IPublicService")]
    public interface IPublicService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_EventDTO/Create", ReplyAction="http://tempuri.org/IServiceOf_EventDTO/CreateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebUI.WcfPublicServiceReference.InvalidEventException), Action="http://tempuri.org/IServiceOf_EventDTO/CreateInvalidEventExceptionFault", Name="InvalidEventException", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary.CustomExceptions")]
        void Create(WebUI.WcfPublicServiceReference.EventDTO obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_EventDTO/Create", ReplyAction="http://tempuri.org/IServiceOf_EventDTO/CreateResponse")]
        System.Threading.Tasks.Task CreateAsync(WebUI.WcfPublicServiceReference.EventDTO obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_EventDTO/Delete", ReplyAction="http://tempuri.org/IServiceOf_EventDTO/DeleteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebUI.WcfPublicServiceReference.CanNotCreateEventSeatException), Action="http://tempuri.org/IServiceOf_EventDTO/DeleteCanNotCreateEventSeatExceptionFault", Name="CanNotCreateEventSeatException", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary.CustomExceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebUI.WcfPublicServiceReference.CanNotDeleteEventException), Action="http://tempuri.org/IServiceOf_EventDTO/DeleteCanNotDeleteEventExceptionFault", Name="CanNotDeleteEventException", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary.CustomExceptions")]
        void Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_EventDTO/Delete", ReplyAction="http://tempuri.org/IServiceOf_EventDTO/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_EventDTO/Update", ReplyAction="http://tempuri.org/IServiceOf_EventDTO/UpdateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebUI.WcfPublicServiceReference.InvalidEventException), Action="http://tempuri.org/IServiceOf_EventDTO/UpdateInvalidEventExceptionFault", Name="InvalidEventException", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary.CustomExceptions")]
        void Update(WebUI.WcfPublicServiceReference.EventDTO obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_EventDTO/Update", ReplyAction="http://tempuri.org/IServiceOf_EventDTO/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(WebUI.WcfPublicServiceReference.EventDTO obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_EventDTO/GetById", ReplyAction="http://tempuri.org/IServiceOf_EventDTO/GetByIdResponse")]
        WebUI.WcfPublicServiceReference.EventDTO GetById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_EventDTO/GetById", ReplyAction="http://tempuri.org/IServiceOf_EventDTO/GetByIdResponse")]
        System.Threading.Tasks.Task<WebUI.WcfPublicServiceReference.EventDTO> GetByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_EventDTO/GetAll", ReplyAction="http://tempuri.org/IServiceOf_EventDTO/GetAllResponse")]
        WebUI.WcfPublicServiceReference.EventDTO[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_EventDTO/GetAll", ReplyAction="http://tempuri.org/IServiceOf_EventDTO/GetAllResponse")]
        System.Threading.Tasks.Task<WebUI.WcfPublicServiceReference.EventDTO[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublicService/GetEventInfo", ReplyAction="http://tempuri.org/IPublicService/GetEventInfoResponse")]
        WebUI.WcfPublicServiceReference.EventInfoDTO GetEventInfo(int eventId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublicService/GetEventInfo", ReplyAction="http://tempuri.org/IPublicService/GetEventInfoResponse")]
        System.Threading.Tasks.Task<WebUI.WcfPublicServiceReference.EventInfoDTO> GetEventInfoAsync(int eventId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublicService/GetAllEventAreasDTOByEventId", ReplyAction="http://tempuri.org/IPublicService/GetAllEventAreasDTOByEventIdResponse")]
        WebUI.WcfPublicServiceReference.EventAreaDTO[] GetAllEventAreasDTOByEventId(int eventId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublicService/GetAllEventAreasDTOByEventId", ReplyAction="http://tempuri.org/IPublicService/GetAllEventAreasDTOByEventIdResponse")]
        System.Threading.Tasks.Task<WebUI.WcfPublicServiceReference.EventAreaDTO[]> GetAllEventAreasDTOByEventIdAsync(int eventId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublicService/GetAllEventSeatDTOByEventId", ReplyAction="http://tempuri.org/IPublicService/GetAllEventSeatDTOByEventIdResponse")]
        WebUI.WcfPublicServiceReference.EventSeatDTO[] GetAllEventSeatDTOByEventId(int eventId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublicService/GetAllEventSeatDTOByEventId", ReplyAction="http://tempuri.org/IPublicService/GetAllEventSeatDTOByEventIdResponse")]
        System.Threading.Tasks.Task<WebUI.WcfPublicServiceReference.EventSeatDTO[]> GetAllEventSeatDTOByEventIdAsync(int eventId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPublicServiceChannel : WebUI.WcfPublicServiceReference.IPublicService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PublicServiceClient : System.ServiceModel.ClientBase<WebUI.WcfPublicServiceReference.IPublicService>, WebUI.WcfPublicServiceReference.IPublicService {
        
        public PublicServiceClient() {
        }
        
        public PublicServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PublicServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PublicServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PublicServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Create(WebUI.WcfPublicServiceReference.EventDTO obj) {
            base.Channel.Create(obj);
        }
        
        public System.Threading.Tasks.Task CreateAsync(WebUI.WcfPublicServiceReference.EventDTO obj) {
            return base.Channel.CreateAsync(obj);
        }
        
        public void Delete(int id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public void Update(WebUI.WcfPublicServiceReference.EventDTO obj) {
            base.Channel.Update(obj);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(WebUI.WcfPublicServiceReference.EventDTO obj) {
            return base.Channel.UpdateAsync(obj);
        }
        
        public WebUI.WcfPublicServiceReference.EventDTO GetById(int id) {
            return base.Channel.GetById(id);
        }
        
        public System.Threading.Tasks.Task<WebUI.WcfPublicServiceReference.EventDTO> GetByIdAsync(int id) {
            return base.Channel.GetByIdAsync(id);
        }
        
        public WebUI.WcfPublicServiceReference.EventDTO[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<WebUI.WcfPublicServiceReference.EventDTO[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public WebUI.WcfPublicServiceReference.EventInfoDTO GetEventInfo(int eventId) {
            return base.Channel.GetEventInfo(eventId);
        }
        
        public System.Threading.Tasks.Task<WebUI.WcfPublicServiceReference.EventInfoDTO> GetEventInfoAsync(int eventId) {
            return base.Channel.GetEventInfoAsync(eventId);
        }
        
        public WebUI.WcfPublicServiceReference.EventAreaDTO[] GetAllEventAreasDTOByEventId(int eventId) {
            return base.Channel.GetAllEventAreasDTOByEventId(eventId);
        }
        
        public System.Threading.Tasks.Task<WebUI.WcfPublicServiceReference.EventAreaDTO[]> GetAllEventAreasDTOByEventIdAsync(int eventId) {
            return base.Channel.GetAllEventAreasDTOByEventIdAsync(eventId);
        }
        
        public WebUI.WcfPublicServiceReference.EventSeatDTO[] GetAllEventSeatDTOByEventId(int eventId) {
            return base.Channel.GetAllEventSeatDTOByEventId(eventId);
        }
        
        public System.Threading.Tasks.Task<WebUI.WcfPublicServiceReference.EventSeatDTO[]> GetAllEventSeatDTOByEventIdAsync(int eventId) {
            return base.Channel.GetAllEventSeatDTOByEventIdAsync(eventId);
        }
    }
}
